name: Android Build and Test

on: [push,pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set Up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run Tests
        run: ./gradlew testDebugUnitTest testReleaseUnitTest
        continue-on-error: true

      - name: Generate Coverage Report
        run: ./gradlew jacocoTestReport

      - name: Build Project
        run: ./gradlew assemble

      - name: Upload coverage to Qlty
        uses: qltysh/qlty-action/coverage@v2
        with:
          token: ${{ secrets.QLTY_COVERAGE_TOKEN }}
          files: app/build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml
          format: jacoco
          skip-missing-files: true
        env:
          JACOCO_SOURCE_PATH: app/src/main/java
